services:
    redis-server:
        image: 'redis'
        volumes:
          - ./redis:/data
        command: ["redis-server", "--protected-mode", "no"]
    node-app:
        restart: always
        build: ./
        image: docker.io/kabhilasha/visits
        ports:
            - "8081:8081"